name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Microservices
    runs-on: ubuntu-latest
    strategy:
      # This matrix allows you to run builds for all services in parallel
      matrix:
        service: [inventory_frontend, inventory, payment]
        include:
          - service: inventory_frontend
            context: ./inventory_frontend
            image_name: inventory_frontend
          - service: inventory
            context: ./inventory
            image_name: inventory
          - service: payment
            context: ./payment
            image_name: payment
          # - service: redis_custom
          #   context: ./redis # Only if you have a custom Dockerfile for Redis
          #   image_name: redis

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.context }}
        push: true
        tags: nitorAcrPoc1.azurecr.io/${{ matrix.image_name }}:${{ github.run_number }}
  
    - name: Summary
      run: echo "Built and pushed ${{ matrix.image_name }}:${{ github.run_number }}"

    - name: Set AKS Context
      uses: azure/aks-set-context@v3
      with:
        resource-group: "rg_poc_1"
        cluster-name: "nitorAksPoc1"

    - name: Deploy to AKS
      run: |
        export IMAGE_TAG=${{ github.run_number }}
        export REGISTRY=nitorAcrPoc1.azurecr.io

        envsubst < k8s/redis-deployment.yml | kubectl apply -f -
        envsubst < k8s/inventory-deployment.yml | kubectl apply -f -
        envsubst < k8s/payment-deployment.yml | kubectl apply -f -
        envsubst < k8s/inventory-frontend-deployment.yml | kubectl apply -f -